api = "0.10"

[buildpack]
  id = "btl/ffmpeg"
  version = "0.0.2"
  name = "FFmpeg Buildpack"
  homepage = "https://github.com/BTLzdravtech/ffmpeg-buildpack"
  description = "Installs FFmpeg packages"
  keywords = ["ffmpeg"]

[[stacks]]
  id = "io.buildpacks.samples.stacks.jammy"
